name: conversion

channels:
    - conda-forge
    - aramislab

dependencies:
    - python>=3.0
    - ipython
    - numpy
    - nibabel
    - dipy
    - psutil
    - plumbum
    - pandas
    - ants=2.2.0
    - git
    - pip:
        - git+https://github.com/mhe/pynrrd.git
